export const cards = [
    {
        path: '/img/1.svg',
        visible: false,
        name: 'youtube',
        checked: false,
    },
    {
        path: '/img/2.svg',
        visible: false,
        name: 'redfl',
        checked: false,
    },
    {
        path: '/img/3.svg',
        visible: false,
        name: 'wordpress',
        checked: false,
    },
    {
        path: '/img/4.svg',
        visible: false,
        name: 'wiki',
        checked: false,
    },
    {
        path: '/img/5.svg',
        visible: false,
        name: 'whatsUp',
        checked: false,
    },
    {
        path: '/img/6.svg',
        visible: false,
        name: 'vimeo',
        checked: false,
    },
    {
        path: '/img/7.svg',
        visible: false,
        name: 'vivi',
        checked: false,
    },
    {
        path: '/img/8.svg',
        visible: false,
        name: 'tweeter',
        checked: false,
    },
    {
        path: '/img/9.svg',
        visible: false,
        name: 'tj',
        checked: false,
    },
    {
        path: '/img/10.svg',
        visible: false,
        name: 'bus',
        checked: false,
    },
    {
        path: '/img/11.svg',
        visible: false,
        name: 'snake',
        checked: false,
    },
    {
        path: '/img/12.svg',
        visible: false,
        name: 'spotify',
        checked: false,
    },
    {
        path: '/img/13.svg',
        visible: false,
        name: 'soundCloud',
        checked: false,
    },
    {
        path: '/img/14.svg',
        visible: false,
        name: 'snap',
        checked: false,
    },
    {
        path: '/img/15.svg',
        visible: false,
        name: 'skype',
        checked: false,
    },
    {
        path: '/img/16.svg',
        visible: false,
        name: 'redCube',
        checked: false,
    },
    {
        path: '/img/17.svg',
        visible: false,
        name: 'blueuzor',
        checked: false,
    },
    {
        path: '/img/18.svg',
        visible: false,
        name: 'redit',
        checked: false,
    },
    {
        path: '/img/2_1.svg',
        visible: false,
        name: 'youtube',
        checked: false,
    },
    {
        path: '/img/2_2.svg',
        visible: false,
        name: 'redfl',
        checked: false,
    },
    {
        path: '/img/2_3.svg',
        visible: false,
        name: 'wordpress',
        checked: false,
    },
    {
        path: '/img/2_4.svg',
        visible: false,
        name: 'wiki',
        checked: false,
    },
    {
        path: '/img/2_5.svg',
        visible: false,
        name: 'whatsUp',
        checked: false,
    },
    {
        path: '/img/2_6.svg',
        visible: false,
        name: 'vimeo',
        checked: false,
    },
    {
        path: '/img/2_7.svg',
        visible: false,
        name: 'vivi',
        checked: false,
    },
    {
        path: '/img/2_8.svg',
        visible: false,
        name: 'tweeter',
        checked: false,
    },
    {
        path: '/img/2_9.svg',
        visible: false,
        name: 'tj',
        checked: false,
    },
    {
        path: '/img/2_10.svg',
        visible: false,
        name: 'bus',
        checked: false,
    },
    {
        path: '/img/2_11.svg',
        visible: false,
        name: 'snake',
        checked: false,
    },
    {
        path: '/img/2_12.svg',
        visible: false,
        name: 'spotify',
        checked: false,
    },
    {
        path: '/img/2_13.svg',
        visible: false,
        name: 'soundCloud',
        checked: false,
    },
    {
        path: '/img/2_14.svg',
        visible: false,
        name: 'snap',
        checked: false,
    },
    {
        path: '/img/2_15.svg',
        visible: false,
        name: 'skype',
        checked: false,
    },
    {
        path: '/img/2_16.svg',
        visible: false,
        name: 'redCube',
        checked: false,
    },
    {
        path: '/img/2_17.svg',
        visible: false,
        name: 'blueuzor',
        checked: false,
    },
    {
        path: '/img/2_18.svg',
        visible: false,
        name: 'redit',
        checked: false,
    },
]
